[versions]
    modopedia = "1.1.0"

# Common
    minecraft = "1.21.1"
    minecraft-range = "[1.21.1,)"
    forgeconfigapi = "21.1.1"
    neoform = "1.21-20240613.152323"
    jei = "19.21.2.313"

# Fabric
    fabric = "0.16.14"
    fabric-api = "0.116.3+1.21.1"

# NeoForge
    neoforge-loader-range = "[4,)"
    neoforge-range = "[21.1.72,)"
    neoforge = "21.1.179"

# Dependencies
    mixin = "0.8.7"
    mixinextras = "0.3.5"
    schoomp = "1.2.6"
    parchment-minecraft = "1.21"
    parchment = "2024.07.28"

# Plugins
    plugin-mod-dev-gradle = "2.0.31-beta"
    plugin-loom = "1.10-SNAPSHOT"
    plugin-minotaur = "2.8.7"
    plugin-curseforge-gradle = "1.1.25"
    plugin-idea-ext = "1.1.8"
    plugin-mixin = "0.7.+"
    plugin-wikitoolkit = "0.2.7"

[libraries]
# Common
    forgeconfigapi-common = { group = "fuzs.forgeconfigapiport", name = "forgeconfigapiport-common-neoforgeapi", version.ref = "forgeconfigapi" }

# Fabric
    forgeconfigapi-fabric = { group = "fuzs.forgeconfigapiport", name = "forgeconfigapiport-fabric", version.ref = "forgeconfigapi" }
    jei-fabric-api = { group = "mezz.jei", name = "jei-1.21.1-fabric-api", version.ref = "jei" }
    jei-fabric = { group = "mezz.jei", name = "jei-1.21.1-fabric", version.ref = "jei" }

# Mixin
    mixin = { group = "org.spongepowered", name = "mixin", version.ref = "mixin" }
    mixinextras-common = { group = "io.github.llamalad7", name = "mixinextras-common", version.ref = "mixinextras" }
    jei-common-api = { group = "mezz.jei", name = "jei-1.21.1-common-api", version.ref = "jei" }

# NeoForge
    jei-neoforge-api = { group = "mezz.jei", name = "jei-1.21.1-neoforge-api", version.ref = "jei" }
    jei-neoforge = { group = "mezz.jei", name = "jei-1.21.1-neoforge", version.ref = "jei" }

# Platform
    neoforge = { group = "net.neoforged", name = "neoforge", version.ref = "neoforge" }
    fabric = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric" }
    fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
    minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }

# Misc
    schoomp = { group = "com.diluv.schoomp", name = "Schoomp", version.ref = "schoomp" }

[plugins]
# Publishing
    minotaur = { id = "com.modrinth.minotaur", version.ref = "plugin-minotaur" }
    curseforgegradle = { id = "net.darkhax.curseforgegradle", version.ref = "plugin-curseforge-gradle" }
    wikitoolkit = { id = "org.moddedmc.wiki.toolkit", version.ref = "plugin-wikitoolkit" }

# Platform
    moddevgradle = { id = "net.neoforged.moddev", version.ref = "plugin-mod-dev-gradle" }
    loom = { id = "fabric-loom", version.ref = "plugin-loom" }

# Misc
    ideaext = { id = "org.jetbrains.gradle.plugin.idea-ext", version.ref = "plugin-idea-ext" }
    mixin = { id = "org.spongepowered.mixin", version.ref = "plugin-mixin" }